# _config.yml

title: "Bobo BC"
description: "My Chirpy Blog"
baseurl: ""  # leave empty for GitHub Pages
url: "https://bobo-bc.github.io"

theme: jekyll-theme-chirpy

# Do NOT set source: docs unless you really have a docs folder
# source: docs   # REMOVE this if it doesn’t exist

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed
