# _tina/schema.yml
collections:
  - name: "posts"
    label: "Blog Posts"
    path: "_posts"
    format: "md"
    frontmatter:
      title: "string"
      date: "datetime"
      tags: "list"
      categories: "list"
      image: "image"
    media:
      publicFolder: "/assets/img"
      mediaRoot: "assets/img"

  - name: "pages"
    label: "Pages"
    path: "_pages"
    format: "md"
    frontmatter:
      title: "string"
      layout: "string"
    media:
      publicFolder: "/assets/img"
      mediaRoot: "assets/img"
